development:
  adapter: postgresql
  database: stacksocial_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: stacksocial_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: stacksocial
  pool: 5
  timeout: 5000
